@startuml

package android{
 abstract class Activity
 abstract class View
 class Button
 class TextView
}

View <|-- Button
View <|-- TextView

class CounterActivity {
 counter : int
 onCreate(Bundle)
}

Activity <|-- CounterActivity

class BallView {
  setPosition(int)
  setOnDropListener(...)
}

View <|-- BallView

Button --* CounterActivity : inc
Button --* CounterActivity : dec
TextView --* CounterActivity : ctr
BallView --* CounterActivity : ball

interface OnDropListener {
  onDrop(int)
}
OnDropListener --+ BallView


@enduml